version: "3"
services:
  birdnet-celery:
  
    build:
      context: .
    image: birdnet
    command: bash -c "celery -A worker.worker worker --autoscale 5,1 --loglevel=INFO -Q birdnet"
    restart: always  
    volumes:
      - /ibed/arise/exportdir:/media/exportdir
    environment: 
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
volumes:
  exportdir:
      external: true
networks:
  network1:
    name: arisemds_vm_scripts_default
    external: true